### ISSUE TITLE
Exeception during install

### ISSUE THREAD

**Issue by BDHU** [starcitizen-lug/lug-helper#64] opened 2023-08-13 21:12 UTC
During the installation step, I encountered the following issue:

```text
Unhandled exception: page fault on read access to 0x060a0091 in 32-bit code (0x01008b39).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:01008b39 ESP:0032f5d4 EBP:0032f5e8 EFLAGS:00010206(  R- --  I   - -P- )
 EAX:0047d3b8 EBX:01002854 ECX:060a0065 EDX:00000000
 ESI:019511c0 EDI:010019f8
Stack dump:
0x0032f5d4:  0047d3b8 fffffff7 019511c0 00000000
0x0032f5e4:  00000000 0032f994 0100b752 010026c0
0x0032f5f4:  010019f8 00000000 00000034 01088100
0x0032f604:  00000000 01000000 00000000 00000000
0x0032f614:  00000002 00000000 0032f664 01009c0c
0x0032f624:  0000138a 00000000 00001389 010a004f
Backtrace:
=>0 0x01008b39 in dxwsetup (+0x8b39) (0x0032f5e8)
  1 0x0100b752 in dxwsetup (+0xb752) (0x0032f994)
  2 0x01008965 in dxwsetup (+0x8965) (0x0032fe08)
  3 0x0100dc6b in dxwsetup (+0xdc6b) (0x0032ff30)
  4 0x7b629db0 in kernel32 (+0x29db0) (0x0032ff48)
  5 0x7bc5c457 in ntdll (+0x5c457) (0x0032ff5c)
  6 0x7bc5cc60 in ntdll (+0x5cc60) (0x0032ffec)
0x01008b39 dxwsetup+0x8b39: call	*0x2c(%ecx)
Modules:
Module	Address			Debug info	Name (77 modules)
PE	01000000-01085000	Export          dxwsetup
PE	62500000-62637000	Deferred        oleaut32
PE	63880000-638aa000	Deferred        wintrust
PE	643c0000-643ea000	Deferred        ws2_32
PE	64a80000-64abc000	Deferred        win32u
PE	65340000-6534a000	Deferred        msimg32
PE	65480000-65515000	Deferred        rpcrt4
PE	65680000-6572e000	Deferred        msvcrt
PE	66080000-660dc000	Deferred        shlwapi
PE	66380000-664be000	Deferred        ole32
PE	66640000-6664d000	Deferred        version
PE	667c0000-667da000	Deferred        shcore
PE	66f80000-66fa5000	Deferred        inseng
PE	67500000-6751b000	Deferred        imm32
PE	67bc0000-67d2f000	Deferred        comctl32
PE	684c0000-68522000	Deferred        combase
PE	68880000-68a48000	Deferred        user32
PE	68cc0000-68d9c000	Deferred        crypt32
PE	69840000-69886000	Deferred        advapi32
PE	6aac0000-6ab9a000	Deferred        ucrtbase
PE	6bb40000-6bb6f000	Deferred        winex11
PE	6bbc0000-6bbeb000	Deferred        sechost
PE	6c100000-6c189000	Deferred        wininet
PE	6da80000-6db0d000	Deferred        gdi32
PE	6e200000-6e217000	Deferred        bcrypt
PE	70380000-70430000	Deferred        urlmon
PE	70d80000-70db8000	Deferred        uxtheme
PE	712c0000-712e0000	Deferred        mpr
PE	71400000-71d46000	Deferred        shell32
PE	7b000000-7b2ab000	Deferred        kernelbase
PE	7b600000-7b662000	Export          kernel32
PE	7bc00000-7bcae000	Export          ntdll
ELF	7d000000-7d005000	Deferred        <wine-loader>
ELF	7d81c000-7d899000	Deferred        libgmp.so.10
ELF	7d9a9000-7d9f6000	Deferred        libhogweed.so.6
ELF	7d9f6000-7da48000	Deferred        libnettle.so.8
ELF	7da48000-7dc00000	Deferred        libunistring.so.2
ELF	7dc00000-7de3c000	Deferred        libgnutls.so.30
ELF	7de3c000-7de42000	Deferred        ws2_32.so
ELF	7de42000-7de48000	Deferred        crypt32.so
ELF	7de48000-7de58000	Deferred        libffi.so.8
ELF	7de58000-7de6f000	Deferred        libtasn1.so.6
ELF	7de6f000-7dec2000	Deferred        libidn2.so.0
ELF	7dec2000-7e006000	Deferred        libp11-kit.so.0
ELF	7e006000-7e011000	Deferred        bcrypt.so
ELF	7e059000-7e062000	Deferred        libxfixes.so.3
ELF	7e062000-7e06f000	Deferred        libxcursor.so.1
ELF	7e06f000-7e084000	Deferred        libxi.so.6
ELF	7e084000-7e089000	Deferred        libxcomposite.so.1
ELF	7e089000-7e097000	Deferred        libxrandr.so.2
ELF	7e097000-7e0a5000	Deferred        libxrender.so.1
ELF	7e0a5000-7e0ac000	Deferred        libxxf86vm.so.1
ELF	7e0ac000-7e0b1000	Deferred        libxinerama.so.1
ELF	7e0b1000-7e0b7000	Deferred        libxau.so.6
ELF	7e0b7000-7e0e7000	Deferred        libxcb.so.1
ELF	7e0e7000-7e23f000	Deferred        libx11.so.6
ELF	7e23f000-7e256000	Deferred        libxext.so.6
ELF	7e256000-7e2d6000	Deferred        winex11.so
ELF	7e40e000-7e43b000	Deferred        libexpat.so.1
ELF	7e43b000-7e490000	Deferred        libfontconfig.so.1
ELF	7e490000-7e52f000	Deferred        libpcre2-8.so.0
ELF	7e52f000-7e552000	Deferred        libbrotlicommon.so.1
ELF	7e552000-7e577000	Deferred        libgraphite2.so.3
ELF	7e577000-7e6e7000	Deferred        libglib-2.0.so.0
ELF	7e6e7000-7e6f5000	Deferred        libbrotlidec.so.1
ELF	7e6f5000-7e818000	Deferred        libharfbuzz.so.0
ELF	7e818000-7e85a000	Deferred        libpng16.so.16
ELF	7e85a000-7e919000	Deferred        libfreetype.so.6
ELF	7e919000-7ea78000	Deferred        win32u.so
ELF	7ea78000-7ec00000	Dwarf           libwine.so.1
ELF	7ee81000-7ee94000	Deferred        libbz2.so.1
ELF	7ee94000-7eeae000	Deferred        libz.so.1
ELF	7eeae000-7eed3000	Deferred        libgcc_s.so.1
ELF	7eed3000-7efa9000	Deferred        libm.so.6
ELF	f7c00000-f7e32000	Deferred        libc.so.6
ELF	f7edd000-f7f88000	Deferred        ntdll.so
ELF	f7f8c000-f7fc4000	Deferred        ld-linux.so.2
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 RSI-Setup-1.6.7.exe
	00000024    0     
	00000114    0     
00000038 services.exe
	0000003c    0     
	00000040    0     wine_rpcrt4_server
	00000054    0     wine_rpcrt4_io
	00000078    0     wine_rpcrt4_io
	000000a0    0     wine_rpcrt4_io
	000000b8    0     wine_rpcrt4_io
	000000f0    0     wine_rpcrt4_io
00000044 winedevice.exe
	00000048    0     
	0000005c    0     
	00000060    0     wine_sechost_service
	00000064    0     
	00000068    0     
	0000006c    0     
	000000c4    0     
00000070 winedevice.exe
	00000074    0     
	0000007c    0     
	00000080    0     wine_sechost_service
	00000084    0     
	00000088    0     
	0000008c    0     
	00000098    0     
	0000009c    0     
00000090 plugplay.exe
	00000094    0     
	000000a4    0     
	000000a8    0     wine_sechost_service
	000000ac    0     wine_rpcrt4_server
000000b0 svchost.exe
	000000b4    0     
	000000bc    0     
	000000c0    0     wine_sechost_service
000000c8 explorer.exe
	000000cc    0     
	000000d8    0     
	000000e4    0     wine_rpcrt4_server
000000dc rpcss.exe
	000000e0    0     
	000000f8    0     
	000000fc    0     wine_sechost_service
	00000100    0     wine_rpcrt4_server
	00000104    0     wine_rpcrt4_server
	0000010c    0     wine_rpcrt4_io
000001e8 dxwebsetup.exe
	000001ec    0     
000001f0 (D) C:\users\me\Temp\IXP000.TMP\dxwsetup.exe
	000001f4    0 <== 
	00000208    0     
00000200 conhost.exe
	00000204    0     
System information:
    Wine build: wine-8.0.2
    Platform: i386 (WOW64)
    Version: Windows 10
    Host system: Linux
    Host version: 6.1.0-11-amd64
```

I installed both lutrics and wine using flatpak. When I do the pre-check, it warned me that no wine is found in the system:

```text
- Wine does not appear to be installed.
    At a minimum, wine dependencies must be installed.
    Please refer to our Quick Start Guide:
    https://starcitizen-lug.github.io
```

Should I install flatpak using `apt`? Or is it ok to use the flatpak version of wine? Any help is appreciated.

**Comment by the-sane** [comment] 2023-08-13 21:18
Hey there! Your best bet is going to be to ask for help in our Discord tech support channel. It's bridged to our Matrix space if you don't have or want to use Discord. The links are on our wiki: https://starcitizen-lug.github.io

You'll find a lot of helpful penguins in there. I'm going to close this issue since it's likely a configuration issue and not a bug with our Helper.

**Closed by the-sane** 2023-08-13 21:18 UTC
