### ISSUE TITLE
Can't select WINE prefix directory in KDE

### ISSUE THREAD

**Issue by HittingSmoke** [starcitizen-lug/lug-helper#18] opened 2021-06-19 15:19 UTC
Manjaro

LUG Helper 1.9
Plasma 5.21.5
KDE Frameworks 5.82.0
Qt 5.12.2
Kernel 5.12.8
Dolphin 21.04.1

When using the "Delete my..." options in LUG, it opens a file select dialog. When I go to my Lutris ~/Games directory and select ./star-citizen then click "Open" nothing happens. If I go into the star-citizen directory and click "Open" nothing happens. The dialog does not close and there is no output on the terminal.

**Comment by the-sane** [comment] 2021-06-21 15:17
@Termuellinator can you look into this? Thanks!

**Comment by Termuellinator** [comment] 2021-06-21 16:45
I tried to reproduce it here on manjaro testing and it works as expected for me. I'm not sure how to narrow down the issue on your side to be honest...
Maybe it's something GTK related i have installed and you don't?

```
~ >>> pacman -Q | grep gtk                                                                                                                                                                                                                         [1]
breeze-gtk 5.22.1-1
colord-gtk 0.2.0-2
gst-plugin-gtk 1.18.4-2
gtk-theme-breath 5.9.0-1
gtk-update-icon-cache 1:4.2.1-2
gtk2 2.24.33-2
gtk3 1:3.24.29-2
gtkglext 1.2.0-13
gtkmm3 3.24.5-2
gtksourceview3 3.24.11+28+g73e57b57-1
gtkspell3 3.0.10-2
kde-gtk-config 5.22.1-1
lib32-gtk2 2.24.33-1
lib32-gtk3 3.24.29-1
lib32-libappindicator-gtk2 12.10.0-12
lib32-libdbusmenu-gtk2 16.04.0-4
lib32-libindicator-gtk2 12.10.1-8
libdbusmenu-gtk2 16.04.0-4
libdbusmenu-gtk3 16.04.0-4
libindicator-gtk2 12.10.1-9
pamac-gtk 10.1.3-3
webkit2gtk 2.32.1-1
wxgtk-common 3.0.5.1-2
wxgtk3 3.0.5.1-2
```

**Comment by the-sane** [comment] 2021-09-18 20:02
@HittingSmoke Are you still having problems with this?  If we can't reproduce it, I'm not sure how to narrow it down. 

As a workaround, you can force the script into text-only mode.  Edit it, scroll all the way to the bottom and change `use_zenity=1` to `use_zenity=0`

The relevant code is here:
https://github.com/the-sane/lug-helper/blob/master/lug-helper.sh#L1281-L1285

**Comment by the-sane** [comment] 2021-12-07 01:27
Going to close this since it's been a few months with no updates.  If you still have a problem and can give us more info to help us reproduce it, go ahead and re-open the issue.

**Closed by the-sane** 2021-12-07 01:27 UTC
