### ISSUE TITLE
[Arch] Preflight Check Lutris Version

### ISSUE THREAD

**Issue by Magnamura** [starcitizen-lug/lug-helper#54] opened 2023-04-21 08:12 UTC
Greetings!
I just switched from Ubuntu to Arch (EndeavorOS) and just made the Preflight check.
It says that `Lutris is out of date. Version 0.5.11 or newer is required.`
When i run `lutris -v` in terminal i'm getting `lutris-0.5.12`.

I won't say by default that the lug-helper has a bug for i'm by all means not an Linux expert.
But I'm trusting lutris here for the Numbers.

o7

**Comment by Termuellinator** [comment] 2023-04-21 08:33
Do you by chance also have the flatpak version installed and not updated or something like that?

**Comment by Magnamura** [comment] 2023-04-21 08:37
The System is a fresh install.
all packages are up to date according to yay
flatpak isn't installed, according to the bash reply `bach: flatpak: command not found`

**Comment by Termuellinator** [comment] 2023-04-21 08:49
that's odd then. Did you install the helper via AUR or manually?
Could you please share the result of `lutris -v | awk -F '-' '{print $2}'`?

**Comment by Magnamura** [comment] 2023-04-21 09:06
I installed the helper manually.
The output of `lutris -v | awk -F '-' '{print $2}'` is ` ` (nothing)
But when i'm running `lutris -v` i'm getting `lutris-0.5.12
Segmentation fault (core dumped)`
And I'm honest: I haven't realized the part `Segmentation fault (core dumped)`. I will investigate...

**Comment by Termuellinator** [comment] 2023-04-21 09:08
if you have installed it manually, make sure you have all the dependecies installed (awk in this case)
The segfault isn't a good thing either of course ^^

**Comment by Magnamura** [comment] 2023-04-21 09:55
So it appeares that i was indeed missing some Stuff.
lutris -d said:
`INFO     2023-04-21 11:08:21,748 [startup.init_lutris:173]:Starting Lutris 0.5.12
INFO     2023-04-21 11:08:21,829 [startup.check_driver:57]:Using NVIDIA drivers 530.41.03 for x86_64
INFO     2023-04-21 11:08:21,829 [startup.check_driver:61]:GPU: NVIDIA GeForce GTX 970
INFO     2023-04-21 11:08:21,830 [startup.check_driver:77]:GPU: 10DE:13C2 1458:367A (nvidia drivers)
ERROR    2023-04-21 11:08:21,830 [startup.check_libs:112]:i386 libGL.so.1 missing (needed by opengl)
ERROR    2023-04-21 11:08:21,830 [startup.check_libs:112]:i386 libvulkan.so.1 missing (needed by vulkan)
ERROR    2023-04-21 11:08:21,830 [startup.check_libs:112]:i386 libgnutls.so.30 missing (needed by gnutls)
`
I fixed it by installing all needed nvidia packages (I'm a derp) and getting now this output:
`INFO     2023-04-21 11:38:51,067 [startup.init_lutris:173]:Starting Lutris 0.5.12
INFO     2023-04-21 11:38:51,151 [startup.check_driver:57]:Using NVIDIA drivers 530.41.03 for x86_64
INFO     2023-04-21 11:38:51,151 [startup.check_driver:61]:GPU: NVIDIA GeForce GTX 970
INFO     2023-04-21 11:38:51,151 [startup.check_driver:77]:GPU: 10DE:13C2 1458:367A (nvidia drivers)
DEBUG    2023-04-21 11:38:51,270 [lutriswindow.update_store:448]:Showing 0 games
INFO     2023-04-21 11:38:51,275 [startup.update_runtimes:218]:Startup complete
`
when i'm `lutris -v` in the terminal, i'm still getting the segfault.

the coredump's output is as followed:
`           PID: 44818 (python3)
           UID: 1000 (magna)
           GID: 1000 (magna)
        Signal: 11 (SEGV)
     Timestamp: Fri 2023-04-21 11:46:49 CEST (4min 18s ago)
  Command Line: python3 /usr/bin/lutris -v
    Executable: /usr/bin/python3.10
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-org.gnome.Terminal.slice/vte-spawn-b8fd6060-d132-4180-8081-a250d7d79eab.scope
          Unit: user@1000.service
     User Unit: vte-spawn-b8fd6060-d132-4180-8081-a250d7d79eab.scope
         Slice: user-1000.slice
     Owner UID: 1000 (magna)
       Boot ID: 79d93dc9753c4bddb9dfcb9fc7ee32d3
    Machine ID: f9beb4e8f11a4639933b48031949406b
      Hostname: amaterasu
       Storage: /var/lib/systemd/coredump/core.python3.1000.79d93dc9753c4bddb9dfcb9fc7ee32d3.44818.1682070409000000.zst (present)
  Size on Disk: 7.2M
       Message: Process 44818 (python3) of user 1000 dumped core.
                
                Stack trace of thread 44818:
                #0  0x00007f990cbedf2b n/a (libgtk-3.so.0 + 0x3edf2b)
                #1  0x00007f990e2383f4 n/a (libgio-2.0.so.0 + 0xa83f4)
                #2  0x00007f990e23c08d n/a (libgio-2.0.so.0 + 0xac08d)
                #3  0x00007f990e2a527e n/a (libgio-2.0.so.0 + 0x11527e)
                #4  0x00007f990e2383f4 n/a (libgio-2.0.so.0 + 0xa83f4)
                #5  0x00007f990e23c08d n/a (libgio-2.0.so.0 + 0xac08d)
                #6  0x00007f990e2951d3 n/a (libgio-2.0.so.0 + 0x1051d3)
                #7  0x00007f990e2383f4 n/a (libgio-2.0.so.0 + 0xa83f4)
                #8  0x00007f990e23842d n/a (libgio-2.0.so.0 + 0xa842d)
                #9  0x00007f990e4bb53b g_main_context_dispatch (libglib-2.0.so.0 + 0x5a53b)
                #10 0x00007f990e518219 n/a (libglib-2.0.so.0 + 0xb7219)
                #11 0x00007f990e4ba1a2 g_main_context_iteration (libglib-2.0.so.0 + 0x591a2)
                #12 0x00007f990e26c4f2 g_application_run (libgio-2.0.so.0 + 0xdc4f2)
                #13 0x00007f990edf24f6 n/a (libffi.so.8 + 0x74f6)
                #14 0x00007f990edeef5e n/a (libffi.so.8 + 0x3f5e)
                #15 0x00007f990edf1b73 ffi_call (libffi.so.8 + 0x6b73)
                #16 0x00007f990e5d7941 n/a (_gi.cpython-310-x86_64-linux-gnu.so + 0x2b941)
                #17 0x00007f990e5d6290 n/a (_gi.cpython-310-x86_64-linux-gnu.so + 0x2a290)
                #18 0x00007f990f162f9c PyObject_Call (libpython3.10.so.1.0 + 0x162f9c)
                #19 0x00007f990f148e4b _PyEval_EvalFrameDefault (libpython3.10.so.1.0 + 0x148e4b)
                #20 0x00007f990f1570e9 _PyFunction_Vectorcall (libpython3.10.so.1.0 + 0x1570e9)
                #21 0x00007f990f14676a _PyEval_EvalFrameDefault (libpython3.10.so.1.0 + 0x14676a)
                #22 0x00007f990f144f80 n/a (libpython3.10.so.1.0 + 0x144f80)
                #23 0x00007f990f1f39e4 PyEval_EvalCode (libpython3.10.so.1.0 + 0x1f39e4)
                #24 0x00007f990f204383 n/a (libpython3.10.so.1.0 + 0x204383)
                #25 0x00007f990f1ffaea n/a (libpython3.10.so.1.0 + 0x1ffaea)
                #26 0x00007f990f0a223f n/a (libpython3.10.so.1.0 + 0xa223f)
                #27 0x00007f990f0a1ef0 _PyRun_SimpleFileObject (libpython3.10.so.1.0 + 0xa1ef0)
                #28 0x00007f990f0a28a3 _PyRun_AnyFileObject (libpython3.10.so.1.0 + 0xa28a3)
                #29 0x00007f990f210b5d Py_RunMain (libpython3.10.so.1.0 + 0x210b5d)
                #30 0x00007f990f1e4f3b Py_BytesMain (libpython3.10.so.1.0 + 0x1e4f3b)
                #31 0x00007f990ee3c790 n/a (libc.so.6 + 0x23790)
                #32 0x00007f990ee3c84a __libc_start_main (libc.so.6 + 0x2384a)
                #33 0x000055c1eef5a045 _start (python3.10 + 0x1045)
                
                Stack trace of thread 44819:
                #0  0x00007f990ef190dd syscall (libc.so.6 + 0x1000dd)
                #1  0x00007f990e5117b5 g_cond_wait (libglib-2.0.so.0 + 0xb07b5)
                #2  0x00007f990e485fb4 n/a (libglib-2.0.so.0 + 0x24fb4)
                #3  0x00007f990e4ecf9e n/a (libglib-2.0.so.0 + 0x8bf9e)
                #4  0x00007f990e4e8315 n/a (libglib-2.0.so.0 + 0x87315)
                #5  0x00007f990ee9ebb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007f990ef20d90 n/a (libc.so.6 + 0x107d90)
                
                Stack trace of thread 44821:
                #0  0x00007f990e4bb81a g_main_context_check (libglib-2.0.so.0 + 0x5a81a)
                #1  0x00007f990e518078 n/a (libglib-2.0.so.0 + 0xb7078)
                #2  0x00007f990e4bac7f g_main_loop_run (libglib-2.0.so.0 + 0x59c7f)
                #3  0x00007f990e29ed5c n/a (libgio-2.0.so.0 + 0x10ed5c)
                #4  0x00007f990e4e8315 n/a (libglib-2.0.so.0 + 0x87315)
                #5  0x00007f990ee9ebb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007f990ef20d90 n/a (libc.so.6 + 0x107d90)
                
                Stack trace of thread 44820:
                #0  0x00007f990ef139df __poll (libc.so.6 + 0xfa9df)
                #1  0x00007f990e51817f n/a (libglib-2.0.so.0 + 0xb717f)
                #2  0x00007f990e4ba1a2 g_main_context_iteration (libglib-2.0.so.0 + 0x591a2)
                #3  0x00007f990e4ba1f2 n/a (libglib-2.0.so.0 + 0x591f2)
                #4  0x00007f990e4e8315 n/a (libglib-2.0.so.0 + 0x87315)
                #5  0x00007f990ee9ebb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007f990ef20d90 n/a (libc.so.6 + 0x107d90)
                
                Stack trace of thread 44832:
                #0  0x00007f990ef190dd syscall (libc.so.6 + 0x1000dd)
                #1  0x00007f990e511d03 g_cond_wait_until (libglib-2.0.so.0 + 0xb0d03)
                #2  0x00007f990e485f83 n/a (libglib-2.0.so.0 + 0x24f83)
                #3  0x00007f990e4ed9fb n/a (libglib-2.0.so.0 + 0x8c9fb)
                #4  0x00007f990e4e8315 n/a (libglib-2.0.so.0 + 0x87315)
                #5  0x00007f990ee9ebb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007f990ef20d90 n/a (libc.so.6 + 0x107d90)
                ELF object binary architecture: AMD x86-64
`
I'm using python 3.10.10 which is the latest version that pacman offers.

And still the Helper insists that my Lutris is out of date, which was the sole reason i opened that ticket :D :bow:

**Comment by Termuellinator** [comment] 2023-04-21 09:57
The helper probably is just confused by the segfault ^^
It's strange though that lutris segfaults with `-v` but runs fine otherwise... :thinking:

**Comment by Termuellinator** [comment] 2023-04-21 10:45
Well, as long as `lutris -v | awk -F '-' '{print $2}'` doesn't produce the right output, the helper won't be able to get the correct version as that's what used to get the current version ^^
If you find out what causes the segfault with `-v`, you can of course report here (and at lutris if applicable) in case someone else encounters it. Till then i guess you're right that closing the issue is the way to go, thank you :)

**Closed by Termuellinator** 2023-04-21 10:45 UTC

**Comment by the-sane** [comment] 2023-04-21 13:29
If you're running a git release of lutris, they did change how the `-v` flag is processed to fix an issue I reported a while back. They could have broken something while doing that.

If you're running the stable release, I don't have any ideas what could be causing the segfault. They have a discord, perhaps you can ask for help there? It'd be good to know why that's happening.
